name: unit-test

on:
  pull_request:

permissions:
  contents: read
  checks: write
  statuses: write

jobs:
  unit-test:
    uses: jucr-io/github-reusable-workflows/.github/workflows/rust-test-v1.yaml@main
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        profile: ["release"]
        toolchain: ["stable"]
        targets:
          - name: "."
            target: "x86_64-unknown-linux-gnu"
          - name: "."
            target: "aarch64-unknown-linux-gnu"
          - name: "."
            target: "aarch64-apple-darwin"
    with:
      profile: ${{ matrix.profile }}
      toolchain: ${{ matrix.toolchain }}
      target: ${{ matrix.targets.target }}
      # features: ${{ matrix.targets.features }}
      name: ${{ matrix.targets.name }}
      rust_log: "debug"
      rust_backtrace: "full"
      rustflags: "-D warnings"
      debug: "false"
